### ISSUE TITLE
Metrics not showing

### ISSUE THREAD

**Issue by davidkazuhiro** [CachetHQ/Cachet#2888]
I'm using the cachethq/docker:2.3.13 Docker image with MySQL and the metrics graph is showing an empty box on the status page.

![image](https://user-images.githubusercontent.com/474054/35372717-c1db3bc6-01de-11e8-964e-f94d91aa2d5a.png)

Looks like some 500 errors are being thrown internally

```
[25-Jan-2018 04:49:22] WARNING: [pool www] child 165 said into stderr: "NOTICE: PHP message: [2018-01-25 04:49:22] development.ERROR: PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'cachet.metric_points' doesn't exist in /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:333"
[25-Jan-2018 04:49:22] WARNING: [pool www] child 165 said into stderr: "Stack trace:"
[25-Jan-2018 04:49:22] WARNING: [pool www] child 165 said into stderr: "#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(333): PDO->prepare('SELECT AVG(mp.`...')"
[25-Jan-2018 04:49:22] WARNING: [pool www] child 165 said into stderr: "#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(706): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'SELECT AVG(mp.`...', Array)"
[25-Jan-2018 04:49:22] WARNING: [pool www] child 165 said into stderr: "#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(669): Illuminate\Database\Connection->runQueryCallback('SELECT AVG(mp.`...', Array, Object(Closure))"
[25-Jan-2018 04:49:22] WARNING: [pool www] child 165 said into stderr: "#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(342): Illuminate\Database\Connection->run('SELECT AVG(mp.`...', Array, Object(Closure))"
[25-Jan-2018 04:49:22] WARNING: [pool www] child 165 said into stderr: "#4 [internal function]: Illuminate\Database\Connection-..."
2018/01/25 04:49:22 [error] 103#103: *357 FastCGI sent in stderr: "PHP message: [2018-01-25 04:49:22] development.ERROR: PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'cachet.metric_points' doesn't exist in /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:333
Stack trace:
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(333): PDO->prepare('SELECT AVG(mp.`...')
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(706): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'SELECT AVG(mp.`...', Array)
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(669): Illuminate\Database\Connection->runQueryCallback('SELECT AVG(mp.`...', Array, Object(Closure))
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(342): Illuminate\Database\Connection->run('SELECT AVG(mp.`...', Array, Object(Closure))
#4 [internal function]: Illuminate\Database\Connection->select(" while reading response header from upstream, client: 10.255.0.6, server: localhost, request: "GET /metrics/1?filter=last_hour HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "cachet.local", referrer: "http://cachet.local/"
10.255.0.6 - - [25/Jan/2018:04:49:22 +0000] "GET /metrics/1?filter=last_hour HTTP/1.1" 500 3187 "http://cachet.local/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:59.0) Gecko/20100101 Firefox/59.0" "-"
```

Metrics is enabled both at /dashboard/metrics/1/edit and at /dashboard/settings/setup

Data also exists.

```
$ curl --request GET --url http://cachet.local/api/v1/metrics/1/points | python -m json.tool
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3103    0  3103    0     0  44595      0 --:--:-- --:--:-- --:--:-- 44971
{
    "data": [
        {
            "calculated_value": 0.197,
            "counter": 1,
            "created_at": "2018-01-25 13:32:31",
            "id": 1,
            "metric_id": 1,
            "updated_at": "2018-01-25 13:32:17",
            "value": 0.197
        },
        {
            "calculated_value": 0.091,
            "counter": 1,
            "created_at": "2018-01-25 13:33:01",
            "id": 2,
            "metric_id": 1,
            "updated_at": "2018-01-25 13:32:48",
            "value": 0.091
        },
        {
            "calculated_value": 0.056,
            "counter": 1,
            "created_at": "2018-01-25 13:33:32",
            "id": 3,
            "metric_id": 1,
            "updated_at": "2018-01-25 13:33:18",
            "value": 0.056
        },
        {
            "calculated_value": 0.066,
            "counter": 1,
            "created_at": "2018-01-25 13:34:02",
            "id": 4,
            "metric_id": 1,
            "updated_at": "2018-01-25 13:33:48",
            "value": 0.066
        },
        {
            "calculated_value": 0.064,
            "counter": 1,
            "created_at": "2018-01-25 13:34:32",
            "id": 5,
            "metric_id": 1,
            "updated_at": "2018-01-25 13:34:19",
            "value": 0.064
        },
        {
            "calculated_value": 0.069,
            "counter": 1,
            "created_at": "2018-01-25 13:35:03",
            "id": 6,
            "metric_id": 1,
            "updated_at": "2018-01-25 13:34:49",
            "value": 0.069
        },
        {
            "calculated_value": 0.131,
            "counter": 1,
            "created_at": "2018-01-25 13:35:33",
            "id": 7,
            "metric_id": 1,
            "updated_at": "2018-01-25 13:35:19",
            "value": 0.131
        },
        {
            "calculated_value": 0.065,
            "counter": 1,
            "created_at": "2018-01-25 13:36:03",
            "id": 8,
            "metric_id": 1,
            "updated_at": "2018-01-25 13:35:50",
            "value": 0.065
        },
        {
            "calculated_value": 0.059,
            "counter": 1,
            "created_at": "2018-01-25 13:36:34",
            "id": 9,
            "metric_id": 1,
            "updated_at": "2018-01-25 13:36:20",
            "value": 0.059
        },
        {
            "calculated_value": 0.353,
            "counter": 1,
            "created_at": "2018-01-25 13:37:04",
            "id": 10,
            "metric_id": 1,
            "updated_at": "2018-01-25 13:36:51",
            "value": 0.353
        },
        {
            "calculated_value": 0.201,
            "counter": 1,
            "created_at": "2018-01-25 13:37:35",
            "id": 11,
            "metric_id": 1,
            "updated_at": "2018-01-25 13:37:21",
            "value": 0.201
        },
        {
            "calculated_value": 0.07,
            "counter": 1,
            "created_at": "2018-01-25 13:38:05",
            "id": 12,
            "metric_id": 1,
            "updated_at": "2018-01-25 13:37:51",
            "value": 0.07
        },
        {
            "calculated_value": 0.077,
            "counter": 1,
            "created_at": "2018-01-25 13:38:35",
            "id": 13,
            "metric_id": 1,
            "updated_at": "2018-01-25 13:38:22",
            "value": 0.077
        },
        {
            "calculated_value": 0.161,
            "counter": 1,
            "created_at": "2018-01-25 13:39:06",
            "id": 14,
            "metric_id": 1,
            "updated_at": "2018-01-25 13:38:52",
            "value": 0.161
        },
        {
            "calculated_value": 0.124,
            "counter": 1,
            "created_at": "2018-01-25 13:39:36",
            "id": 15,
            "metric_id": 1,
            "updated_at": "2018-01-25 13:39:22",
            "value": 0.124
        },
        {
            "calculated_value": 0.194,
            "counter": 1,
            "created_at": "2018-01-25 13:40:07",
            "id": 16,
            "metric_id": 1,
            "updated_at": "2018-01-25 13:39:53",
            "value": 0.194
        },
        {
            "calculated_value": 0.057,
            "counter": 1,
            "created_at": "2018-01-25 13:40:37",
            "id": 17,
            "metric_id": 1,
            "updated_at": "2018-01-25 13:40:23",
            "value": 0.057
        },
        {
            "calculated_value": 0.076,
            "counter": 1,
            "created_at": "2018-01-25 13:41:07",
            "id": 18,
            "metric_id": 1,
            "updated_at": "2018-01-25 13:40:53",
            "value": 0.076
        },
        {
            "calculated_value": 0.079,
            "counter": 1,
            "created_at": "2018-01-25 13:41:38",
            "id": 19,
            "metric_id": 1,
            "updated_at": "2018-01-25 13:41:24",
            "value": 0.079
        },
        {
            "calculated_value": 0.081,
            "counter": 1,
            "created_at": "2018-01-25 13:42:08",
            "id": 20,
            "metric_id": 1,
            "updated_at": "2018-01-25 13:41:54",
            "value": 0.081
        }
    ],
    "meta": {
        "pagination": {
            "count": 20,
            "current_page": 1,
            "links": {
                "next_page": "http://cachet.local/api/v1/metrics/1/points?page=2",
                "previous_page": null
            },
            "per_page": 20,
            "total": 50,
            "total_pages": 3
        }
    }
}
```

Any idea what's going wrong?

**Comment by uxen-ab** [comment]
Hi, could you post a dump in order to we are able to reproduce your problem?

**Comment by davidkazuhiro** [comment]
How do I do that?

**Comment by BerkanYildiz** [comment]
I have the same problem:
![image](https://user-images.githubusercontent.com/15068742/35419441-3d38ec7e-0238-11e8-8843-cbdf840f1b11.png)

**Comment by BerkanYildiz** [comment]
Okay, i fixed it. 
In fact, i was using cloudflare with the "RocketScript" feature enabled, which means every .js being loaded on the page, was loaded asynchronously, not synchronously, thus the 'Chart' variable was null.

**Comment by davidkazuhiro** [comment]
@BerkanYildiz maybe that's a different issue than this one?

**Comment by BerkanYildiz** [comment]
Well, obviously.

`[25-Jan-2018 04:49:22] WARNING: [pool www] child 165 said into stderr: "NOTICE: PHP message: [2018-01-25 04:49:22] development.ERROR: PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'cachet.metric_points' doesn't exist in /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:333"`

Your database is corrupted, you should make a backup and reinstall it properly.

**Comment by uxen-ab** [comment]
@davidkazuhiro to do a dump you can use `mysqldump` or `phpmyadmin `. Then try to reinstall it properly, and why not import your previously dumped database.

**Comment by davidkazuhiro** [comment]
@BerkanYildiz @jbrooksuk I wiped everything and reinstalled but still have the same issue.
Though when I say reinstall, I'm just using the official Docker image.

Why isn't the table 'cachet.metric_points' being created?

As mentioned above, the API is returning metric points so it's not like the data isn't in the DB, so this seems like a bug to me...

**Comment by davidkazuhiro** [comment]
I prepared detailed steps on how to reproduce and posted a new issue (#2916) because I haven't gotten any response since @jbrooksuk closed this issue

**Comment by jbrooksuk** [comment]
Sorry, I'm not sure why this issue was closed.

Have you ran `php artisan migrate`? What version of Cachet are you using? Are you using 2.3 with a table prefix? If so, you'll need to upgrade to the latest 2.3 tag.
